### ISSUE TITLE
main.py 代码里面看不到加载哪个embeding模型呀

### ISSUE THREAD

**Issue by qianbaidu1266** [luler/hello_embedding#1]
main.py 代码里面看不到加载哪个embeding模型呀

**Comment by luler** [comment]
![360截图20240329171442983](https://github.com/luler/hello_embedding/assets/34400577/161e5ebe-f5ed-4586-be02-f20ce3ca40d6)
这里指定了向量模型，默认是BAAI/bge-large-zh-v1.5，可以自行在huggingface.co找其他模型替代
